### ISSUE TITLE
Catchable fatal error: Object of class ILess_FileInfo

### ISSUE THREAD

**Issue by srjlewis** [mishal/iless#26]
I know this is incorrect syntax but the exception is not handled properly.

``` css
.test{
  background-color: darken("#ffffff",2%);
}
```

The full error is

```
Catchable fatal error: Object of class ILess_FileInfo could not be converted to string in /path_to_code/public_html/library/classes/shared/ILess/Exception.php on line 185
```
